name: Unit Test
on:
  pull_request:
    branches: [main]
    types:
      - opened

jobs:
  setupJDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java Sdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Unit Test
        run: ./gradlew :domain:test ui:navigation:test :ui:theme:test
        continue-on-error: false

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0

      - name: Detekt
        run: ./gradlew detekt
        continue-on-error: false